name: ci
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Tests (auth-api + notes-api)
        run: |
          pytest -q services/auth/tests services/notes/tests
